---
title: "Vector Practice Exercise"
output: html_notebook
---

##### **Create a vector with the numbers 1 to 10. Also check of the object is a vector or not**

```{r}
vec1<- c(1:10)
vec1
class(vec1)

is.vector(vec1)

#creating vector with seqence function

vec2<- seq(1,10,by=2)
vec2
class(vec2)

is.vector(vec2)


```

##### **Create a vector with the letters A to F.**
```{r}
vec3 <- LETTERS[1:6]
vec3
```
##### **Create a vector with 5 elements, all initialized to 0.**
```{r}
vec4 <- numeric(5)
vec4
class(vec4)
is.vector(vec4)
```

```{r}

```

```{r}
vec5 <- rep(0,5)
vec5
```

```{r}
vec6 <- seq(0,0, length.out = 5)
vec6

```

##### **Create a vector with the numbers 1 to 100, skipping every other number.**
```{r}
vec7 <- seq(1,100, by= 2)
vec7
```
##### **Create a vector containing the square roots of the numbers from 1 to 10.**
```{r}
vec8 <- sqrt(seq(1,10))
vec8
```

```{r}
vec9 <- sqrt(1:10)
vec9
```

```{r}
sqrt_vec <- numeric(10)
for(i in 1:10)
{
  sqrt_vec <- sqrt(i)
  
}
sqrt_vec
```

```{r}
sqrt_vec1 <- sapply(1:10, sqrt)
sqrt_vec1
```

